# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bs-platform-7.2.2" = {
      name = "bs-platform";
      packageName = "bs-platform";
      version = "7.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs-platform/-/bs-platform-7.2.2.tgz";
        sha512 = "PWcFfN+jCTtT/rMaHDhKh+W9RUTpaRunmSF9vbLYcrJbpgCNW6aFKAY33u0P3mLxwuhshN3b4FxqGUBPj6exZQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "react-16.13.1" = {
      name = "react";
      packageName = "react";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.13.1.tgz";
        sha512 = "YMZQQq32xHLX0bz5Mnibv1/LHb3Sqzngu7xstSM+vrkE5Kzr9xE0yMByK5kMoTK30YVJE61WfbxIFFvfeDKT1w==";
      };
    };
    "react-dom-16.13.1" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz";
        sha512 = "81PIMmVLnCNLO/fFOQxdQkvEq/+Hfpv24XNJfpyZhTRfO0QcmQIF/PgCa1zCOj2w1hrn12MFLyaJ/G0+Mxtfag==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "reason-react-0.7.0" = {
      name = "reason-react";
      packageName = "reason-react";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reason-react/-/reason-react-0.7.0.tgz";
        sha512 = "czR/f0lY5iyLCki9gwftOFF5Zs40l7ZSFmpGK/Z6hx2jBVeFDmIiXB8bAQW/cO6IvtuEt97OmsYueiuOYG9XjQ==";
      };
    };
    "scheduler-0.19.1" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.19.1.tgz";
        sha512 = "n/zwRWRYSUj0/3g/otKDRPMh6qv2SYMWNq85IEa8iZyAv8od9zDYpGSnpBEjNgcMNq6Scbu5KfIPxNF72R/2EA==";
      };
    };
  };
  args = {
    name = "ttsmagic-cards-frontend";
    packageName = "ttsmagic-cards-frontend";
    version = "0.0.0";
    src = ../frontend;
    dependencies = [
      sources."bs-platform-7.2.2"
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-16.13.1"
      sources."react-dom-16.13.1"
      sources."react-is-16.13.1"
      sources."reason-react-0.7.0"
      sources."scheduler-0.19.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = https://ttsmagic.cards/;
      license = "UNLICENSED";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}