[workspace]

members = [
    "ttsmagic-s3",
    "ttsmagic-server",
    "ttsmagic-types",
    "ttsmagic-frontend",
]

exclude = [
  "ttsmagic-frontend/wasm",
]

[profile.release]
debug = true
lto = "thin"
